import { ExecutionContext, InternalServerErrorException } from '@nestjs/common';

import { getUser } from './get-user.decorator';

// jest.mock('@nestjs/common', () => ({
//   createParamDecorator: jest.fn(),
//   InternalServerErrorException:
//     jest.requireActual('@nestjs/common').InternalServerErrorException,
// }));
jest.mock('@nestjs/common', () => {
    const current = jest.requireActual('@nestjs/common');
    return {
        ...current,
        createParamDecorator: jest.fn((fn) => fn),
    };
});

describe('GetUser Decorator', () => {
    const mockExecutionContext = {
        switchToHttp: jest.fn().mockReturnValue({
        getRequest: jest.fn().mockReturnValue({
            user: {
            id: '1',
            name: 'John Doe',
            },
        }),
        }),
    } as unknown as ExecutionContext;

    it('should return the user from the request', () => {
        const result = getUser(null, mockExecutionContext);

        expect(result).toEqual({ id: '1', name: 'John Doe' });
    });

    it('should return the user name from the request', () => {
        const result = getUser('name', mockExecutionContext);
        expect(result).toEqual('John Doe');
    });

    it('should throw an internal server error if user not found', () => {
        const mockExecutionContext = {
        switchToHttp: jest.fn().mockReturnValue({
            getRequest: jest.fn().mockReturnValue({
            user: null,
            }),
        }),
        } as unknown as ExecutionContext;

        try {
            getUser(null, mockExecutionContext);
            expect(true).toBe(false);
        } catch (error) {
            expect(error).toBeInstanceOf(InternalServerErrorException);
            expect(error.message).toBe('User not found (request)');
        }
    });
});
